on:
  push:
    tags:
      - "v*"

jobs:
  export_game:
    runs-on: ubuntu-latest
    name: Export Game
    steps:
      - name: Checkout Files
        uses: actions/checkout@v3.3.0
        with:
          submodules: "recursive"

      - name: Install Wine
        id: wine_install
        run: |
          sudo apt install wine64
          echo "WINE_PATH=$(which wine64)" >> $GITHUB_OUTPUT

      - name: Export
        id: export
        uses: firebelley/godot-export@v5.1.0
        with:
          godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/4.0.2/Godot_v4.0.2-stable_linux.x86_64.zip
          godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/4.0.2/Godot_v4.0.2-stable_export_templates.tpz
          relative_project_path: .
          archive_output: true
          wine_path: ${{ steps.wine_install.outputs.WINE_PATH }}

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: create release
        uses: ncipollo/release-action@v1.12.0
        with:
          generateReleaseNotes: true
          tag: ${{ github.ref_name }}
          artifacts: ${{ steps.export.outputs.archive_directory }}/*
